name: Manual Static OpenCV Build & Release

# 允许手动触发工作流
on:
  workflow_dispatch:
    inputs:
      opencv_version:
        description: '要编译的 OpenCV 版本 (e.g., 4.9.0)'
        required: true
        default: '4.9.0'

env:
  OPENCV_VERSION: ${{ github.event.inputs.opencv_version }}
  INSTALL_DIR: ${{ github.workspace }}/opencv_static_install

jobs:
  build-linux-static:
    runs-on: ubuntu-latest
    
    # === 关键修复：添加写入权限 ===
    permissions:
      contents: write # 允许 GITHUB_TOKEN 创建 Releases 和 Tags
    # ==========================
    
    steps:
      - name: Checkout OpenCV Source Code
        uses: actions/checkout@v4
        with:
          repository: opencv/opencv
          ref: ${{ env.OPENCV_VERSION }} 

      - name: Checkout Build Scripts
        uses: actions/checkout@v4
        with:
          path: build-scripts

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential libssl-dev libtbb-dev libopenexr-dev zip

      - name: Build OpenCV
        run: |
          chmod +x build-scripts/build.sh
          OPENCV_SOURCE_DIR=${{ github.workspace }}/opencv build-scripts/build.sh
        env:
          OPENCV_VERSION: ${{ env.OPENCV_VERSION }}
          INSTALL_DIR: ${{ env.INSTALL_DIR }}

      - name: Move Package to Workspace
        run: |
          mv ${{ env.INSTALL_DIR }}/opencv-static-${{ env.OPENCV_VERSION }}-linux-x64.zip ${{ github.workspace }}/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.workspace }}/opencv-static-${{ env.OPENCV_VERSION }}-linux-x64.zip
          name: OpenCV Static Build ${{ env.OPENCV_VERSION }} (Linux x64)
          tag_name: opencv-static-${{ env.OPENCV_VERSION }} 
          draft: false
          prerelease: false
